# Generated by Django 4.2.3 on 2023-07-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThirdsParties',
            new_name='ThirdParties',
        ),
    ]
