# Generated by Django 4.2.3 on 2023-07-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0002_rename_thirdsparties_thirdparties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparties',
            name='third_type_id',
            field=models.CharField(choices=[('NIT', 'Nit'), ('CC', 'CÃ©dula de Ciudadania'), ('CE', 'CÃ©dula de Extranjeria'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('NU', 'Nu'), ('RC', 'Registro Civil'), ('NE', 'Sin identificaciÃ³n del exterior o para uso definido por la DIAN')], max_length=3, verbose_name='Tipo de Identificación del Tercero'),
        ),
    ]
