# Generated by Django 4.2.3 on 2023-07-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0003_alter_thirdparties_third_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparties',
            name='third_adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del Tercero'),
        ),
        migrations.AlterField(
            model_name='thirdparties',
            name='third_regime',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Regimen Simple'), (2, 'Regimen Ordinario'), (3, 'Responsable de IVA'), (4, 'No Responsable de IVA')], default=1, verbose_name='Regimen Tributario de Tercero'),
            preserve_default=False,
        ),
    ]
