# Generated by Django 4.2.3 on 2023-07-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0004_alter_thirdparties_third_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Category Id')),
                ('nombre', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.PositiveIntegerField(verbose_name='Product Id')),
                ('id_third_parties', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Identificación del Tercero')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Sub Category Id')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Subcategory Description')),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='general_data.categories')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
                'db_table': 'subcategories',
            },
        ),
        migrations.DeleteModel(
            name='ThirdParties',
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory_id',
            field=models.ForeignKey(db_column='subcategory_id', on_delete=django.db.models.deletion.CASCADE, to='general_data.subcategories'),
        ),
    ]
