# Generated by Django 4.2.3 on 2023-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0005_categories_products_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Sub Category Id'),
        ),
    ]
